version: "3.8"

services:

  wschat_db:
    image: elasticsearch:8.5.2
    container_name: wschat_db
    ports:
      - "20002:9200"
      - "20003:9300"
    environment:
      discovery.type: single-node
      http.cors.enabled: true
      http.cors.allow-origin: "https://app.elasticvue.com"
      xpack.security.enabled: false
